version: "3"
services:
  front_end:
    build: ./FrontEnd
    image: front_end
    container_name: front_end
    ports:
      - 8888:3000
    depends_on:
      - redis
    volumes:
      - ./FrontEnd/ServiceFrontEnd/views:/opt/servicefront/views
      - ./FrontEnd/ServiceFrontEnd/public/styles:/opt/servicefront/public/styles
      - ./FrontEnd/ServiceFrontEnd/public/js:/opt/servicefront/public/js

  users:
    build: ./Users
    image: users
    container_name: users
    depends_on:
      - redis
    volumes:
      - ./commonDb.db:/opt/users/commonDb.db
  
  posts:
    build: ./Posts
    image: posts
    container_name: posts
    depends_on:
      - redis
    volumes:
      - ./commonDb.db:/opt/posts/commonDb.db

  relations:
    build: ./Relations
    image: relations
    container_name: relations
    depends_on:
      - redis
    volumes:
      - ./commonDb.db:/opt/relations/commonDb.db

  redis:
    image: redis
    container_name: redis