version: "3"
services:
  front_end:
    image: mikolaj6/front_end
    container_name: front_end
    ports:
      - 8888:3000
    depends_on:
      - redis
    volumes:
      - ./FrontEnd/ServiceFrontEnd/views:/opt/servicefront/views
      - ./FrontEnd/ServiceFrontEnd/public/styles:/opt/servicefront/public/styles
      - ./FrontEnd/ServiceFrontEnd/public/js:/opt/servicefront/public/js

  users:
    image: mikolaj6/users
    container_name: users
    depends_on:
      - redis
  
  posts:
    image: mikolaj6/posts
    container_name: posts
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis